"""fawaterak — unofficial Python SDK for the Fawaterak API v3."""

from importlib.metadata import PackageNotFoundError, version

from .client import FawaterakClient
from .config import Config
from .exceptions import (
	FawaterakAPIException,
	FawaterakAuthException,
	FawaterakConfigException,
	FawaterakConnectionException,
	FawaterakException,
	FawaterakTemporaryException,
	FawaterakValidationException,
	FawaterakWebhookException,
)
from .models import (
	CardPaymentResult,
	CartItem,
	Customer,
	DirectPaymentResult,
	DiscountData,
	HostedCheckoutResult,
	MobileWalletResult,
	Page,
	PaymentMethod,
	PaymentMethodHistoryItem,
	PaymentResult,
	RedirectionUrls,
	ReferenceCodeResult,
	TaxData,
	TransactionData,
	TransactionExportItem,
	TransactionResult,
	UnknownPaymentResult,
	parse_payment_data,
)
from .webhooks import (
	CancelWebhookEvent,
	FailedWebhookEvent,
	PaidWebhookEvent,
	RefundWebhookEvent,
	TokenizationWebhookEvent,
	WebhookType,
	parse_cancel_webhook,
	parse_failed_webhook,
	parse_paid_webhook,
	parse_refund_webhook,
	parse_tokenization_webhook,
	parse_webhook,
	verify_cancel_webhook,
	verify_failed_webhook,
	verify_paid_webhook,
	verify_refund_webhook,
	verify_tokenization_webhook,
	verify_webhook,
)

try:
	__version__ = version("fawaterak")
except PackageNotFoundError:
	__version__ = "unknown"

__all__ = [
	"CancelWebhookEvent",
	"CardPaymentResult",
	"CartItem",
	"Config",
	"Customer",
	"DirectPaymentResult",
	"DiscountData",
	"FailedWebhookEvent",
	"FawaterakAPIException",
	"FawaterakAuthException",
	"FawaterakClient",
	"FawaterakConfigException",
	"FawaterakConnectionException",
	"FawaterakException",
	"FawaterakTemporaryException",
	"FawaterakValidationException",
	"FawaterakWebhookException",
	"HostedCheckoutResult",
	"MobileWalletResult",
	"Page",
	"PaidWebhookEvent",
	"PaymentMethod",
	"PaymentMethodHistoryItem",
	"PaymentResult",
	"RedirectionUrls",
	"ReferenceCodeResult",
	"RefundWebhookEvent",
	"TaxData",
	"TokenizationWebhookEvent",
	"TransactionData",
	"TransactionExportItem",
	"TransactionResult",
	"UnknownPaymentResult",
	"WebhookType",
	"__version__",
	"parse_cancel_webhook",
	"parse_failed_webhook",
	"parse_paid_webhook",
	"parse_payment_data",
	"parse_refund_webhook",
	"parse_tokenization_webhook",
	"parse_webhook",
	"verify_cancel_webhook",
	"verify_failed_webhook",
	"verify_paid_webhook",
	"verify_refund_webhook",
	"verify_tokenization_webhook",
	"verify_webhook",
]
